# Generated by Django 5.1.1 on 2024-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'пункт меню', 'verbose_name_plural': 'пункты меню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название пункта'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
