# Generated by Django 5.1.1 on 2024-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_title_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='SLUG'),
        ),
    ]
