# Generated by Django 5.1.1 on 2024-09-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='slug',
            new_name='url',
        ),
    ]
