# Generated by Django 5.1.1 on 2024-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_slug_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
